---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hkdcfgyd/bigwings/
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R old $DEPLOYPATH
    - /bin/cp *.* $DEPLOYPATH
    